'use client'

import { useUIStore } from '@/stores/ui-store'
import { T } from '@/lib/i18n'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { FileText, Plus, FileCheck, FileClock, AlertTriangle } from 'lucide-react'

const DOC_TYPES = [
  { key: 'technical_doc', article: 'Art. 11', en: 'Technical Documentation', es: 'Documentación técnica' },
  { key: 'conformity_declaration', article: 'Art. 47', en: 'EU Declaration of Conformity', es: 'Declaración de conformidad UE' },
  { key: 'risk_management_plan', article: 'Art. 9', en: 'Risk Management Plan', es: 'Plan de gestión de riesgos' },
  { key: 'data_governance', article: 'Art. 10', en: 'Data Governance Documentation', es: 'Documentación de gobernanza de datos' },
  { key: 'transparency_notice', article: 'Art. 13', en: 'Transparency Notice', es: 'Aviso de transparencia' },
  { key: 'human_oversight_plan', article: 'Art. 14', en: 'Human Oversight Plan', es: 'Plan de supervisión humana' },
]

export default function DocumentsPage() {
  const { lang } = useUIStore()

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">{T[lang].documents}</h1>
          <p className="text-muted-foreground mt-1">
            {lang === 'es' ? 'Documentación obligatoria generada por IA según el EU AI Act' :
             'Mandatory documentation generated by AI according to the EU AI Act'}
          </p>
        </div>
        <Button className="bg-blue-600 hover:bg-blue-700" disabled>
          <Plus className="mr-2 h-4 w-4" />
          {lang === 'es' ? 'Generar documento' : 'Generate Document'}
        </Button>
      </div>

      {/* Stats */}
      <div className="grid gap-4 sm:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              {lang === 'es' ? 'Total documentos' : 'Total Documents'}
            </CardTitle>
            <FileText className="h-5 w-5 text-blue-600" />
          </CardHeader>
          <CardContent><p className="text-3xl font-bold">0</p></CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              {lang === 'es' ? 'Aprobados' : 'Approved'}
            </CardTitle>
            <FileCheck className="h-5 w-5 text-emerald-500" />
          </CardHeader>
          <CardContent><p className="text-3xl font-bold">0</p></CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              {lang === 'es' ? 'Pendientes de revisión' : 'Pending Review'}
            </CardTitle>
            <FileClock className="h-5 w-5 text-yellow-500" />
          </CardHeader>
          <CardContent><p className="text-3xl font-bold">0</p></CardContent>
        </Card>
      </div>

      {/* Document types */}
      <Card>
        <CardHeader>
          <CardTitle className="text-lg">
            {lang === 'es' ? 'Tipos de documentos obligatorios' : 'Required Document Types'}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {DOC_TYPES.map((doc) => (
              <div key={doc.key} className="flex items-center justify-between p-3 rounded-lg border">
                <div className="flex items-center gap-3">
                  <FileText className="h-5 w-5 text-blue-600 shrink-0" />
                  <div>
                    <p className="text-sm font-medium">{lang === 'es' ? doc.es : doc.en}</p>
                    <p className="text-xs text-muted-foreground">{doc.article}</p>
                  </div>
                </div>
                <Badge variant="secondary">
                  {lang === 'es' ? 'No generado' : 'Not generated'}
                </Badge>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Empty state note */}
      <Card>
        <CardContent className="flex items-center gap-3 py-4">
          <AlertTriangle className="h-5 w-5 text-yellow-500 shrink-0" />
          <p className="text-sm text-muted-foreground">
            {lang === 'es'
              ? 'Para generar documentos, primero registra un sistema AI y completa su evaluación de riesgo.'
              : 'To generate documents, first register an AI system and complete its risk assessment.'}
          </p>
        </CardContent>
      </Card>
    </div>
  )
}
