'use client'

import Link from 'next/link'
import { useUIStore } from '@/stores/ui-store'
import { useSystemsStore } from '@/stores/systems-store'
import { useDocumentsStore } from '@/stores/documents-store'
import { getRequiredDocs } from '@/lib/doc-templates'
import { T } from '@/lib/i18n'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { FileText, FileCheck, FileClock, Cpu, ArrowRight } from 'lucide-react'
import type { RiskCategory } from '@/types/database'

const RISK_COLORS: Record<RiskCategory, string> = {
  prohibited: 'bg-red-600 text-white',
  high_risk: 'bg-orange-500 text-white',
  limited_risk: 'bg-yellow-500 text-black',
  minimal_risk: 'bg-green-500 text-white',
}

function riskLabel(lang: keyof typeof T, category: RiskCategory | null) {
  if (!category) return '--'
  const map: Record<RiskCategory, keyof typeof T['en']> = {
    prohibited: 'prohibited',
    high_risk: 'highRisk',
    limited_risk: 'limitedRisk',
    minimal_risk: 'minimalRisk',
  }
  return T[lang][map[category]]
}

export default function DocumentsPage() {
  const { lang } = useUIStore()
  const { systems } = useSystemsStore()
  const { documents } = useDocumentsStore()

  const totalDocs = documents.length
  const approvedDocs = documents.filter((d) => d.status === 'approved').length
  const pendingDocs = documents.filter((d) => d.status === 'review').length

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold">{T[lang].documents}</h1>
        <p className="text-muted-foreground mt-1">
          {lang === 'es'
            ? 'Documentacion obligatoria generada por IA segun el EU AI Act'
            : 'Mandatory documentation generated by AI according to the EU AI Act'}
        </p>
      </div>

      {/* Stats */}
      <div className="grid gap-4 sm:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              {lang === 'es' ? 'Total documentos' : 'Total Documents'}
            </CardTitle>
            <FileText className="h-5 w-5 text-blue-600" />
          </CardHeader>
          <CardContent>
            <p className="text-3xl font-bold">{totalDocs}</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              {lang === 'es' ? 'Aprobados' : 'Approved'}
            </CardTitle>
            <FileCheck className="h-5 w-5 text-emerald-500" />
          </CardHeader>
          <CardContent>
            <p className="text-3xl font-bold">{approvedDocs}</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              {T[lang].pendingReviews}
            </CardTitle>
            <FileClock className="h-5 w-5 text-yellow-500" />
          </CardHeader>
          <CardContent>
            <p className="text-3xl font-bold">{pendingDocs}</p>
          </CardContent>
        </Card>
      </div>

      {/* Systems with document progress */}
      {systems.length === 0 ? (
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-16 text-center">
            <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-muted">
              <Cpu className="h-8 w-8 text-muted-foreground" />
            </div>
            <h3 className="text-lg font-semibold">
              {lang === 'es' ? 'Registra un sistema AI primero' : 'Register an AI system first'}
            </h3>
            <p className="mt-1 text-sm text-muted-foreground max-w-md">
              {lang === 'es'
                ? 'Para generar documentos de cumplimiento, primero registra un sistema AI y completa su clasificacion de riesgo.'
                : 'To generate compliance documents, first register an AI system and complete its risk classification.'}
            </p>
            <Link href="/systems/new" className="mt-4">
              <Button>
                {lang === 'es' ? 'Registrar sistema' : 'Register System'}
              </Button>
            </Link>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-4">
          {systems.map((system) => {
            const requiredDocs = getRequiredDocs(system.category)
            const systemDocs = documents.filter((d) => d.ai_system_id === system.id)
            const generatedCount = systemDocs.length
            const requiredCount = requiredDocs.length
            const progress = requiredCount > 0 ? Math.round((generatedCount / requiredCount) * 100) : 0

            return (
              <Card key={system.id}>
                <CardContent className="flex items-center gap-4 py-4">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <h3 className="font-semibold truncate">{system.name}</h3>
                      {system.category && (
                        <span
                          className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium shrink-0 ${RISK_COLORS[system.category]}`}
                        >
                          {riskLabel(lang, system.category)}
                        </span>
                      )}
                    </div>
                    <p className="text-sm text-muted-foreground mb-2">
                      {generatedCount}/{requiredCount}{' '}
                      {lang === 'es' ? 'documentos' : 'documents'}
                    </p>
                    {/* Progress bar */}
                    <div className="w-full h-2 bg-muted rounded-full overflow-hidden">
                      <div
                        className={`h-full rounded-full transition-all ${
                          progress === 100
                            ? 'bg-emerald-500'
                            : progress > 0
                              ? 'bg-blue-500'
                              : 'bg-gray-300 dark:bg-gray-600'
                        }`}
                        style={{ width: `${Math.min(progress, 100)}%` }}
                      />
                    </div>
                  </div>
                  <Link href={`/documents/${system.id}`}>
                    <Button variant="outline" size="sm">
                      {lang === 'es' ? 'Generar documentos' : 'Generate Documents'}
                      <ArrowRight className="ml-1.5 h-4 w-4" />
                    </Button>
                  </Link>
                </CardContent>
              </Card>
            )
          })}
        </div>
      )}
    </div>
  )
}
