'use client'

import { marked } from 'marked'

export async function exportDocumentToPDF(title: string, content: string, systemName: string) {
  // Dynamic import to avoid SSR issues
  const html2pdf = (await import('html2pdf.js')).default

  const htmlContent = marked.parse(content) as string

  const wrapper = document.createElement('div')
  wrapper.innerHTML = `
    <div style="font-family: 'Helvetica Neue', Arial, sans-serif; padding: 40px; color: #1a1a1a; max-width: 800px; margin: 0 auto;">
      <div style="text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 3px solid #2563EB;">
        <div style="display: inline-block; background: #2563EB; color: white; font-weight: bold; font-size: 18px; width: 40px; height: 40px; line-height: 40px; border-radius: 8px; margin-bottom: 10px;">C</div>
        <h1 style="margin: 10px 0 5px; font-size: 24px; color: #2563EB;">COMPLYZE</h1>
        <p style="margin: 0; font-size: 12px; color: #666;">EU AI Act Compliance Platform</p>
      </div>
      <div style="margin-bottom: 30px; padding: 15px; background: #f8f9fa; border-radius: 8px; border-left: 4px solid #2563EB;">
        <p style="margin: 0 0 5px; font-size: 11px; color: #666;">AI SYSTEM</p>
        <p style="margin: 0; font-size: 14px; font-weight: 600;">${systemName}</p>
      </div>
      <div style="font-size: 13px; line-height: 1.7;">
        ${htmlContent}
      </div>
      <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #eee; text-align: center;">
        <p style="font-size: 10px; color: #999;">Generated by Complyze — EU AI Act Compliance Platform</p>
        <p style="font-size: 10px; color: #999;">This document is AI-generated and should be reviewed by qualified personnel before use.</p>
        <p style="font-size: 10px; color: #999;">Date: ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}</p>
      </div>
    </div>
  `

  const filename = `${systemName.replace(/[^a-zA-Z0-9]/g, '-')}_${title.replace(/[^a-zA-Z0-9]/g, '-')}.pdf`

  await html2pdf()
    .set({
      margin: [10, 10, 10, 10],
      filename,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
    } as Record<string, unknown>)
    .from(wrapper)
    .save()
}

export async function exportAllDocumentsToPDF(
  documents: { title: string; content: string }[],
  systemName: string
) {
  for (const doc of documents) {
    await exportDocumentToPDF(doc.title, doc.content, systemName)
    // Small delay between downloads so browser doesn't block them
    await new Promise(r => setTimeout(r, 500))
  }
}
