'use client'

function mdToHtml(md: string): string {
  return md
    // Headers
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    // Bold
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    // Italic
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    // Horizontal rules
    .replace(/^---$/gm, '<hr>')
    // Tables
    .replace(/^\|(.+)\|$/gm, (match) => {
      const cells = match.split('|').filter(c => c.trim())
      if (cells.every(c => /^[\s-:]+$/.test(c))) return '' // separator row
      const tag = 'td'
      const row = cells.map(c => `<${tag}>${c.trim()}</${tag}>`).join('')
      return `<tr>${row}</tr>`
    })
    // Wrap consecutive tr in table
    .replace(/((<tr>.*<\/tr>\n?)+)/g, '<table><tbody>$1</tbody></table>')
    // Unordered lists
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/((<li>.*<\/li>\n?)+)/g, '<ul>$1</ul>')
    // Paragraphs (lines that aren't already HTML)
    .replace(/^(?!<[hultdao]|<\/|<br|<hr|<table|<strong)(.+)$/gm, '<p>$1</p>')
    // Clean up empty lines
    .replace(/\n{2,}/g, '\n')
}

function buildHTML(title: string, content: string, systemName: string): string {
  const htmlContent = mdToHtml(content)
  const date = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${title} — ${systemName}</title>
<style>
  @media print {
    body { margin: 0; padding: 20px; }
    .no-print { display: none !important; }
  }
  body {
    font-family: 'Helvetica Neue', Arial, sans-serif;
    color: #1a1a1a;
    max-width: 800px;
    margin: 0 auto;
    padding: 40px;
    line-height: 1.7;
    font-size: 13px;
  }
  .header {
    text-align: center;
    margin-bottom: 40px;
    padding-bottom: 20px;
    border-bottom: 3px solid #2563EB;
  }
  .logo {
    display: inline-block;
    background: #2563EB;
    color: white;
    font-weight: bold;
    font-size: 18px;
    width: 40px;
    height: 40px;
    line-height: 40px;
    border-radius: 8px;
    margin-bottom: 10px;
  }
  .header h1 { margin: 10px 0 5px; font-size: 24px; color: #2563EB; }
  .header p { margin: 0; font-size: 12px; color: #666; }
  .system-info {
    margin-bottom: 30px;
    padding: 15px;
    background: #f8f9fa;
    border-radius: 8px;
    border-left: 4px solid #2563EB;
  }
  .system-info .label { margin: 0 0 5px; font-size: 11px; color: #666; text-transform: uppercase; }
  .system-info .value { margin: 0; font-size: 14px; font-weight: 600; }
  .content h1 { font-size: 22px; color: #1a1a1a; margin-top: 30px; border-bottom: 2px solid #eee; padding-bottom: 8px; }
  .content h2 { font-size: 18px; color: #2563EB; margin-top: 25px; }
  .content h3 { font-size: 15px; margin-top: 20px; }
  .content table { width: 100%; border-collapse: collapse; margin: 15px 0; font-size: 12px; }
  .content th, .content td { border: 1px solid #ddd; padding: 8px 10px; text-align: left; }
  .content th { background: #f5f5f5; font-weight: 600; }
  .content ul, .content ol { padding-left: 20px; }
  .content li { margin-bottom: 5px; }
  .content strong { color: #1a1a1a; }
  .content hr { border: none; border-top: 1px solid #eee; margin: 20px 0; }
  .footer {
    margin-top: 40px;
    padding-top: 20px;
    border-top: 2px solid #eee;
    text-align: center;
    font-size: 10px;
    color: #999;
  }
  .footer p { margin: 3px 0; }
  .print-btn {
    position: fixed;
    top: 20px;
    right: 20px;
    background: #2563EB;
    color: white;
    border: none;
    padding: 12px 24px;
    border-radius: 8px;
    font-size: 14px;
    font-weight: 600;
    cursor: pointer;
    z-index: 1000;
    box-shadow: 0 2px 8px rgba(0,0,0,0.2);
  }
  .print-btn:hover { background: #1d4ed8; }
</style>
</head>
<body>
  <button class="print-btn no-print" onclick="window.print()">
    Save as PDF / Print
  </button>

  <div class="header">
    <div class="logo">C</div>
    <h1>COMPLYZE</h1>
    <p>EU AI Act Compliance Platform</p>
  </div>

  <div class="system-info">
    <p class="label">AI System</p>
    <p class="value">${systemName}</p>
  </div>

  <div class="content">
    ${htmlContent}
  </div>

  <div class="footer">
    <p>Generated by Complyze — EU AI Act Compliance Platform</p>
    <p>This document is AI-generated and should be reviewed by qualified personnel before use.</p>
    <p>Date: ${date}</p>
  </div>
</body>
</html>`
}

export function exportDocumentToPDF(title: string, content: string, systemName: string) {
  const html = buildHTML(title, content, systemName)
  const win = window.open('', '_blank')
  if (win) {
    win.document.write(html)
    win.document.close()
  }
}

export function exportAllDocumentsToPDF(
  documents: { title: string; content: string }[],
  systemName: string
) {
  // Combine all documents into one page
  const allContent = documents.map(doc =>
    `# ${doc.title}\n\n${doc.content}\n\n---\n\n`
  ).join('')

  const html = buildHTML('All Compliance Documents', allContent, systemName)
  const win = window.open('', '_blank')
  if (win) {
    win.document.write(html)
    win.document.close()
  }
}
